name: showit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  shimmer_animation: ^2.1.0+1
  timeago: ^3.3.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/assets

  integrations:
    flutter_svg: true
