name: showit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  formz: ^0.6.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  loading_animation_widget: ^1.2.0+4
  shimmer_animation: ^2.1.0+1
  sliver_tools: ^0.2.10
  timeago: ^3.4.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/illustration/
    - assets/svgs/
    - assets/svgs/social_media/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/assets

  integrations:
    flutter_svg: true
